service: serverless-http-api-typescript
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  question:
    handler: src/handlers/question.handler
    events:
      - httpApi:
          path: /get/question
          method: get

  answer:
    handler: src/handlers/answer.handler
    events:
      - httpApi:
          path: /post/answer
          method: post

custom:
  serverless-offline:
    httpPort: 8080
    stageVariables:
      environment: "dev"

plugins:
  - serverless-plugin-typescript
  - serverless-offline
